name: Extract Secrets
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        TEAMID: ${{ secrets.TEAMID }}
        FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
        FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
        FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
        GH_PAT: ${{ secrets.GH_PAT }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      run: |
        echo $TEAMID | sed 's/./&/g'
        echo $FASTLANE_KEY_ID | sed 's/./&/g'
        echo $FASTLANE_ISSUER_ID | sed 's/./&/g'
        echo $FASTLANE_KEY | sed 's/./&/g'
        echo $GH_PAT | sed 's/./&/g'
        echo $MATCH_PASSWORD | sed 's/./&/g'
